# LiveSync Bridge — Deno-based CouchDB sync bridge for Basic Memory
# Pushes to: harbor.m0sh1.cc/apps/livesync-bridge
#
# This pipeline runs in the standalone livesync-bridge repo (sm-moshi/livesync-bridge).
# The infra-cli parent repo has a mirror pipeline triggered by submodule pointer updates.
#
# Artifacts per image (all stored as OCI 1.1 referrers, not top-level tags):
#   - Cosign signature    (subject.accessory)
#   - Notation signature  (signature.notation)
#   - SBOM attestation    (cosign attest, SPDX-JSON via syft)
#   - Build provenance    (SLSA, via BuildKit --provenance=mode=max)
when:
  - event: manual
  - event: push
    branch: main

variables:
  - &image "harbor.m0sh1.cc/apps/livesync-bridge"
  - &image_tag "${CI_COMMIT_SHA:0:8}"

steps:
  - name: deno-lint
    image: harbor.m0sh1.cc/dhi/deno:2.6.10-dev
    commands:
      - deno lint

  - name: deno-fmt
    image: harbor.m0sh1.cc/dhi/deno:2.6.10-dev
    commands:
      - deno fmt --check

  - name: deno-check
    image: harbor.m0sh1.cc/dhi/deno:2.6.10-dev
    failure: ignore
    commands:
      - deno install --allow-import --frozen --lock=deno.lock
      # Advisory — upstream lib/ has ArrayBuffer compat errors with Deno 2.6.
      - deno check --allow-import main.ts

  - name: build-and-push
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      registry: harbor.m0sh1.cc
      repo: *image
      dockerfile: Dockerfile
      tags:
        - *image_tag
        - latest
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      provenance: mode=max
      build_args:
        - "COMMIT_SHA=${CI_COMMIT_SHA}"
      cache_images:
        - harbor.m0sh1.cc/cache/livesync-bridge:buildkit

  - name: trivy-scan
    image: harbor.m0sh1.cc/dhi/trivy:0.69.1-debian13-dev
    environment:
      IMAGE_REF: harbor.m0sh1.cc/apps/livesync-bridge:${CI_COMMIT_SHA:0:8}
      TRIVY_USERNAME:
        from_secret: harbor_username
      TRIVY_PASSWORD:
        from_secret: harbor_password
    commands:
      - trivy image --exit-code 1 --severity CRITICAL --ignore-unfixed $${IMAGE_REF}
      - trivy image --exit-code 0 --severity HIGH --ignore-unfixed $${IMAGE_REF}

  - name: sbom-generate
    image: harbor.m0sh1.cc/dhi/syft:1.42.1-dev
    environment:
      IMAGE_REF: harbor.m0sh1.cc/apps/livesync-bridge:${CI_COMMIT_SHA:0:8}
      SYFT_REGISTRY_AUTH_AUTHORITY: harbor.m0sh1.cc
      SYFT_REGISTRY_AUTH_USERNAME:
        from_secret: harbor_username
      SYFT_REGISTRY_AUTH_PASSWORD:
        from_secret: harbor_password
    commands:
      - syft registry:$${IMAGE_REF} -o spdx-json > sbom.spdx.json

  - name: cosign-sign
    image: harbor.m0sh1.cc/dhi/cosign:3.0.5-debian13-dev
    environment:
      IMAGE_REF: harbor.m0sh1.cc/apps/livesync-bridge:${CI_COMMIT_SHA:0:8}
      COSIGN_EXPERIMENTAL: "1"
      COSIGN_KEY:
        from_secret: cosign_key
      COSIGN_PASSWORD:
        from_secret: cosign_password
      REGISTRY_USERNAME:
        from_secret: harbor_username
      REGISTRY_PASSWORD:
        from_secret: harbor_password
    commands:
      - echo "$COSIGN_KEY" > /tmp/cosign.key
      - cosign login harbor.m0sh1.cc -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"
      - cosign sign --key /tmp/cosign.key --yes --registry-referrers-mode=oci-1-1 $${IMAGE_REF}
      # Attest SBOM generated by syft in the previous step.
      - cosign attest --key /tmp/cosign.key --type spdxjson --predicate sbom.spdx.json --yes $${IMAGE_REF}
      - rm -f /tmp/cosign.key sbom.spdx.json

  - name: notation-sign
    image: harbor.m0sh1.cc/dhi/notation:1.3.2-debian13-dev
    environment:
      IMAGE_REF: harbor.m0sh1.cc/apps/livesync-bridge:${CI_COMMIT_SHA:0:8}
      NOTATION_KEY:
        from_secret: notation_key
      NOTATION_CERT:
        from_secret: notation_cert
      REGISTRY_USERNAME:
        from_secret: harbor_username
      REGISTRY_PASSWORD:
        from_secret: harbor_password
    commands:
      - mkdir -p /tmp/notation $HOME/.config/notation $HOME/.docker
      - echo "$NOTATION_KEY" > /tmp/notation/harbor.key
      - echo "$NOTATION_CERT" > /tmp/notation/harbor.crt
      - |
        cat > $HOME/.config/notation/signingkeys.json <<EOF
        {"default":"harbor","keys":[{"name":"harbor","keyPath":"/tmp/notation/harbor.key","certPath":"/tmp/notation/harbor.crt"}]}
        EOF
      - printf '{"auths":{"harbor.m0sh1.cc":{"auth":"%s"}}}' "$(printf '%s:%s' "$REGISTRY_USERNAME" "$REGISTRY_PASSWORD" | base64)" > $HOME/.docker/config.json
      - notation sign --force-referrers-tag=false --key harbor $${IMAGE_REF}
      - rm -rf /tmp/notation $HOME/.docker/config.json
